apiVersion: v1
kind: Namespace
metadata:
  name: openhands

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands-app
  namespace: openhands
  labels:
    app: openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
    spec:
      containers:
        - name: openhands-app
          image: docker.all-hands.dev/all-hands-ai/openhands:0.24
          imagePullPolicy: Always
          env:
            - name: SANDBOX_RUNTIME_CONTAINER_IMAGE
              value: "docker.all-hands.dev/all-hands-ai/runtime:0.24-nikolaik"
            - name: LOG_ALL_EVENTS
              value: "true"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: openhands-state
              mountPath: /.openhands-state
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: openhands-state
          hostPath:
            path: /home/gravity/.openhands-state

---
apiVersion: v1
kind: Service
metadata:
  name: openhands-service
  namespace: openhands
spec:
  type: NodePort
  selector:
    app: openhands
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000  # Change this if necessary
