replicaCount: 1

image:
  repository: docker.all-hands.dev/all-hands-ai/openhands
  tag: "0.24"
  pullPolicy: Always

service:
  type: NodePort
  port: 3000
  nodePort: 30000

env:
  SANDBOX_RUNTIME_CONTAINER_IMAGE: "docker.all-hands.dev/all-hands-ai/runtime:0.24-nikolaik"
  LOG_ALL_EVENTS: "true"

volumes:
  dockerSockPath: /var/run/docker.sock
  openhandsStatePath: /home/gravity/.openhands-state
