apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
    spec:
      containers:
        - name: openhands
          image: {{ .Values.openhands.image }}
          env:
            - name: LLM_API_KEY
              value: "ollama"
            - name: LLM_BASE_URL
              value: "http://192.168.1.171:31434/"
            - name: LLM_OLLAMA_BASE_URL
              value: "http://192.168.1.171:31434/"
            - name: SANDBOX_RUNTIME_CONTAINER_IMAGE
              value: "docker.all-hands.dev/all-hands-ai/runtime:0.24-nikolaik"
            - name: LOG_ALL_EVENTS
              value: "true"
          ports:
            - containerPort: {{ .Values.openhands.port }}
          volumeMounts:
            - name: openhands-state
              mountPath: "/.openhands-state"
      volumes:
        - name: openhands-state
          hostPath:
            path: {{ .Values.openhands.volumePath }}
            type: DirectoryOrCreate