apiVersion: v1
kind: Service
metadata:
  name: openhands
spec:
  selector:
    app: openhands
  type: NodePort
  ports:
    - port: {{ .Values.openhands.port }}
      targetPort: {{ .Values.openhands.port }}
      nodePort: {{ .Values.openhands.nodePort }}
      protocol: TCP
      name: http
      
  
