apiVersion: v1
kind: Service
metadata:
  name: openhands-service
  namespace: openhands
spec:
  type: {{ .Values.service.type }}
  selector:
    app: openhands
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
